package com.secrethitler.ai.enums;

public enum SuspicionAction {
	GOVERNMENT_DENIED_VOTE,
	FAILED_VETO,
	VOTE_CHOICE_RESULT,
	KILLED_PLAYER,
	CHANCELLOR_VETO,
	SUCCESSFUL_VETO,
	RUNNING_MATE_CHOSEN,
	PRESIDENTIAL_CANDIDATE_CHOSEN,
}
